const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
let mode='content',version=0,approved=false,currentFlags=[];
const meta={content:['AI Content Generator','Create marketing content from a simple business brief.'],social:['Social Media Assistant','Turn a product idea into platform-ready social copy.'],script:['Scriptwriting Assistant','Build a short-form video script with clear beats.'],branding:['Branding Assistant','Shape positioning, voice, promise, and taglines.']};
function setMode(m){mode=m;$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.mode===m));$('#modeTitle').textContent=meta[m][0];$('#modeDesc').textContent=meta[m][1];$('#empty').classList.remove('hidden');$('#result').classList.add('hidden');version=0;approved=false;currentFlags=[];$('#version').textContent='Version 0';}
$$('.nav').forEach(n=>n.onclick=()=>setMode(n.dataset.mode));
async function health(){try{const r=await fetch('/api/health');const d=await r.json();$('#statusDot').style.background=d.aiConnected?'#18835b':'#e0a52b';$('#statusText').textContent=d.aiConnected?'AI connected · '+d.model:'Demo mode · add API key for live AI';}catch{$('#statusDot').style.background='#d44';$('#statusText').textContent='Offline';}}
function flags(list){currentFlags=list||[];$('#flagCount').textContent=currentFlags.length;$('#flags').innerHTML=currentFlags.length?currentFlags.map(f=>`<div class="flag"><strong>${escapeHtml(f.type)}</strong>${escapeHtml(f.note)}</div>`).join(''):'<div class="flag safe"><strong>✓ No automatic flags</strong>Still review factual claims before publishing.</div>'}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function generate(action='generate'){const brief=$('#brief').value.trim();if(!brief){$('#brief').focus();return}const btn=$('#generate');btn.textContent='Generating…';document.body.classList.add('loading');try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,brief,audience:$('#audience').value,tone:$('#tone').value,platform:$('#platform').value,goal:$('#goal').value,action,draft:$('#draft').value})});const d=await r.json();if(!r.ok)throw new Error(d.error);version++;approved=false;$('#version').textContent='Version '+version;$('#draft').value=d.text;$('#provider').textContent=d.provider==='OpenAI Responses API'?'LIVE AI':'DEMO AI';$('#model').textContent=d.model||'local demo';$('#time').textContent=new Date(d.generatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});flags(d.flags);$('#approvalText').textContent='Not approved. Review the draft and any flags first.';$('#approve').textContent='✓ Approve draft';$('#approve').classList.remove('approved');$('#empty').classList.add('hidden');$('#result').classList.remove('hidden');}catch(e){alert('Generation failed: '+e.message)}finally{btn.textContent='✦ Generate with AI';document.body.classList.remove('loading')}}
$('#generate').onclick=()=>generate();$('#regen').onclick=()=>generate('regenerate');
$('#clear').onclick=()=>{$('#brief').value='';$('#audience').value='';$('#goal').value='';$('#draft').value='';$('#empty').classList.remove('hidden');$('#result').classList.add('hidden');version=0;approved=false;currentFlags=[];$('#version').textContent='Version 0'};
$('#draft').addEventListener('input',()=>{approved=false;$('#approve').classList.remove('approved');$('#approve').textContent='✓ Approve draft';$('#approvalText').textContent='Edited draft — review again before approval.';flags(localFlags($('#draft').value))});
function localFlags(text){const out=[];const tests=[['Numeric claim',/\b\d+(?:\.\d+)?%|\b\d+(?:\.\d+)?x\b/i,'Check percentages, growth figures, or quantified performance claims.'],['Superlative',/\b(best|#1|number one|world-class|guaranteed|perfect|ultimate)\b/i,'Check whether this superlative is objectively supportable.'],['Health/safety claim',/\b(cure|treats|prevents|safe for|clinically proven)\b/i,'Verify health, safety, or clinical claims before publishing.'],['Price/offer',/[$₦€£]\s?\d|\b(free|discount|sale|off)\b/i,'Confirm current price, promotion, availability, and terms.']];for(const [type,re,note] of tests)if(re.test(text))out.push({type,note});return out}
$('#approve').onclick=()=>{approved=!approved;$('#approve').classList.toggle('approved',approved);$('#approve').textContent=approved?'✓ Approved by human':'✓ Approve draft';$('#approvalText').textContent=approved?'Approved for export/publishing.':'Not approved. Review the draft and any flags first.'};
function getSaved(){try{return JSON.parse(localStorage.getItem('sellerspark_history')||'[]')}catch{return[]}}
function renderHistory(){const h=getSaved();$('#historyCount').textContent=h.length;$('#historyList').innerHTML=h.length?h.map((x,i)=>`<div class="history-item"><div class="hi-main"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.mode)} · ${x.approved?'approved':'draft'} · ${new Date(x.time).toLocaleString()}</small></div><button onclick="loadHistory(${i})">Load</button></div>`).join(''):'<div class="history-empty">No saved drafts yet.</div>'}
window.loadHistory=i=>{const x=getSaved()[i];if(!x)return;mode=x.mode||'content';setMode(mode);$('#brief').value=x.brief||'';$('#audience').value=x.audience||'';$('#tone').value=x.tone||'Professional';$('#platform').value=x.platform||'Instagram';$('#goal').value=x.goal||'';$('#draft').value=x.text;$('#empty').classList.add('hidden');$('#result').classList.remove('hidden');$('#provider').textContent=x.provider||'AI';$('#model').textContent=x.model||'saved';$('#time').textContent=new Date(x.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});flags(x.flags||[]);approved=Boolean(x.approved);$('#approve').classList.toggle('approved',approved);$('#approve').textContent=approved?'✓ Approved by human':'✓ Approve draft';$('#approvalText').textContent=approved?'Approved for export/publishing.':'Loaded saved draft.';version=x.version||1;$('#version').textContent='Version '+version;};
$('#save').onclick=()=>{if(!$('#draft').value.trim())return;const h=getSaved();h.unshift({title:($('#brief').value||'Untitled draft').slice(0,70),brief:$('#brief').value,audience:$('#audience').value,tone:$('#tone').value,platform:$('#platform').value,goal:$('#goal').value,mode,text:$('#draft').value,flags:currentFlags,approved,provider:$('#provider').textContent,model:$('#model').textContent,version,time:new Date().toISOString()});localStorage.setItem('sellerspark_history',JSON.stringify(h.slice(0,20)));renderHistory();$('#save').textContent='Saved ✓';setTimeout(()=>$('#save').textContent='Save to history',1000)};
$('#clearHistory').onclick=()=>{localStorage.removeItem('sellerspark_history');renderHistory()};
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#draft').value)}catch{const t=document.createElement('textarea');t.value=$('#draft').value;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}$('#copy').textContent='Copied ✓';setTimeout(()=>$('#copy').textContent='Copy',1000)};
$('#download').onclick=()=>downloadFile('sellerspark-draft.txt',$('#draft').value,'text/plain');
$('#evidence').onclick=()=>{const evidence={app:'SellerSpark AI',track:'BuildFest 2026 · Track 2: AI for Content & Creativity',mode,brief:$('#brief').value,version,provider:$('#provider').textContent,model:$('#model').textContent,flags:currentFlags,approved,generatedAt:$('#time').textContent,draft:$('#draft').value};downloadFile('sellerspark-demo-evidence.json',JSON.stringify(evidence,null,2),'application/json')};
function downloadFile(name,text,type){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
health();renderHistory();setMode('content');
